title: Md. Shamiul Islam 
description: Fresh Graduate
baseurl: "/remple/"
url: ""
photo_url: "my-photo.jpg"

# This is an optional section
# You can skip filling in one or more of the items in this section
email: "shamiulislam15@gmail.com"
linkedin: "http://linkedin.com/in/s4m15v0"
github: "https://github.com/s4m15v0"
website: "http://s4m15v0.github.io/"
medium: "https://tahanima.medium.com/"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
